### ISSUE TITLE
赤外線の性能調査

### ISSUE THREAD

**Issue by 0g3** [bolg-developers/bolg#16]

**Comment by Nagisa-Takeuchi** [comment]
使用赤外線LED
SID1K10CM

測定条件
送信側は本番環境（esp32,トランジスタドライブ回路）
場所はラボで、障害物等は無し。
送受信共に机に固定

LED*1
390cm 66.66%
400cm 40%

LED*2
390cm 80%
400cm 30%

確率は各30回測定した平均値。
送信信号はA90（16）
赤外線フォーマットはSONYのものを使用。


以上の結果から、LEDの数は精度の向上には有効だが、到達距離の延伸効果は認められず。
一般的に光の波長は長いほうが遠距離へ到達する能力が高いが、現状使用している波長（940nm）以上の近赤外線LEDの目処はたっておらず、これ以上の距離通信距離を確保するならば新たな情報収集及びレンズ等を用いた収束、延伸手段の模索が必要不可欠である。


しかしながら現在の射程（4m弱）でも室内を想定した戦闘（CQB）ならば実用に耐えうるものと考える。
