### ISSUE TITLE
原プランを実行する

### ISSUE THREAD

**Issue by 0g3** [bolg-developers/bolg#31]
抵抗値の変更

**Comment by 0g3** [comment]
これいつ頃までにできそうとかありますか？

**Comment by Nagisa-Takeuchi** [comment]
ラボが使え次第、かな。
回路の形はそのままでいけるから、問題は計測。
朝起きれたら最短明日の朝。

**Comment by Nagisa-Takeuchi** [comment]
原プランの検証結果
LED*1
抵抗値を15Ωから12Ω（絶対最大定格（これ以上電流を流すと燃える））に変更

結果
距離400cmで受信精度53.3%を記録。

特記無き項目は前回の赤外線性能テストに準ずる。
なお、引き続き桝井プランと組み合わせて検証を行う。
結果は桝井プランの項目へ記述する。
