### ISSUE TITLE
桝井プランを実行する

### ISSUE THREAD

**Issue by Nagisa-Takeuchi** [bolg-developers/bolg#48]
銃身をつけて拡散を抑える。

**Comment by Nagisa-Takeuchi** [comment]
今回の検証は原プランによる改良の上で行われたものである。
LED*1
LED抵抗12Ω
ベース抵抗22Ω
回路構成は赤外線性能テストと同じである。


結果(測定は各30回)

銃身 プラスチック(黒)
距離400cm
銃身長6cm
口径6mm
受信精度56.6%

銃身 アルミ(元タッチペン)
距離400cm
銃身長10cm
口径3mm
受信精度60%

銃身 丸めた紙(内側をペンで黒く塗った物)
距離400cm
銃身長20cm
口径8mm
受信精度86.6%

銃身 一個上と同じ
距離550cm
銃身長20cm
口径8mm
受信精度66.6%

以上の結果から、銃身は受信精度の向上及び受信距離の延伸に効果的であると認められる。
今回は資材不足でこれ以上の検証はできなかったが、さらなる長銃身や小口径銃身も検証する価値があると思われる。
ともあれ、実銃の拳銃における有効射程とほぼ同程度(4~6m)の距離において60%以上の精度が出せたのは進展である。

尚、前回の赤外線性能テストが朝に行われたのに対し、今回の検証は夜間かつ一部消灯した環境で行われている為、厳密には同条件ではない。

**Comment by 0g3** [comment]
ないす！！
