### ISSUE TITLE
IR送信回路のミス

### ISSUE THREAD

**Issue by Nagisa-Takeuchi** [bolg-developers/bolg#5]
赤外線送信回路のトランジスタ取り付け向きが間違っていると思われる。

**Comment by 0g3** [comment]
べつのissue切っちゃったけど、ややこしいのでここに結果書いてください！！

**Comment by Nagisa-Takeuchi** [comment]
本日回路修正及び送信試験完了

環境
送信　ESP32(モバイルバッテリー駆動)
受信　Arduino(PC電源)
蛍光灯照明下において

送信信号　SONYフォーマットにて「A90」

結果
短距離(3~4m)での受信精度は気持ち向上(10回送信中9回を正常に受信)したように感じられる。
しかし、遠距離(5m以上)になると、受信は可能であるものの、正しく受信できない(不正な値を受信する)状態になる。
正面以外の角度では距離に関わらず信号の損壊が認められる(A90以外の値がシリアルモニタに出てくる)。

今回の試験方法は完璧とは言い難く(受信機は机上に静置、送信機は手で持ち上げた状態であったため完全に正面からの送受信とは言えず)、送信機及び受信機を完全に固定した状態での再試験が必要ではないか。
その場合、自宅環境での試験の実施は困難であるため、ラボ等で数人の人員を用いて再試験を行うべきではないかと考えるものである。

**Comment by Nagisa-Takeuchi** [comment]
追記
現在使用中の部品

赤外線LED　SID1K10CM
赤外線受信モジュール　IRM3638N3

**Comment by 0g3** [comment]
`A90`というのは16進数の`0xA90`のことだね。

正面以外の角度が受信できないことはゲーム仕様上問題になる？

**Comment by 0g3** [comment]
> しかし、遠距離(5m以上)になると、受信は可能であるものの、正しく受信できない(不正な値を受信する)状態になる。

これは5m以上だと必ず送信データが破損するという意味で捉えていいのかな？

**Comment by Nagisa-Takeuchi** [comment]
A90は16進数0xa90で間違いない。
正面以外で受信できないのは、レーザー収束の手間が省けるのでむしろ好都合。

5m以上離れると、ごくまれに受信できることもある、程度。実用にはたえない。
ただし、これは正確に正面からの照射ではなかった可能性がある。

**Comment by 0g3** [comment]
> ラボ等で数人の人員を用いて再試験を行うべき
これは具体的には最低何人必要？

**Comment by Nagisa-Takeuchi** [comment]
2人かな。
受信モニター要員と、送信機微調整係。

**Comment by 0g3** [comment]
結果: #16
