### ISSUE TITLE
androidディレクトリの追加

### ISSUE THREAD

**Issue by deodorantpower** [bolg-developers/bolg#60]

**Comment by deodorantpower** [comment]
feat/60/androidディレクトリの追加
でブランチ切って、
add android
git commit -m "ディレクトリの追加"
git push -u origin feat/60/androidディレクトリの追加
したらエラー出てしまった　↓
remote: Permission to bolg-developers/bolg.git denied to deodorantpower.
fatal: unable to access 'https://github.com/bolg-developers/bolg/': The requested URL returned error: 403

**Comment by 0g3** [comment]
UI周りのコード追加
