### ISSUE TITLE
赤外線に用いる信号として扱える整数について

### ISSUE THREAD

**Issue by 0g3** [bolg-developers/bolg#8]
どのような範囲の整数を扱うことができますか？

**Comment by Nagisa-Takeuchi** [comment]
最低でも12ビット。
サンプル改変して試したのが12ビットの信号。
16進数"0xa90"をテストデータとして送信していた。
おそらくもっと大きな値も扱えるが、ネット上の記事に最大値に関する記述が見つけられない。
明日、32bit及び64bitデータの送受信を試してみる。

**Comment by 0g3** [comment]
12ビットいけるなら大丈夫だね。
ひとつのルームに4096人より多くの人間が参加することはないでしょ？笑

**Comment by Nagisa-Takeuchi** [comment]
ありえないね。
あと、たぶん信号は短ければ短いほどいい。
受信時に取り落としにくくなるし、送信も短時間で終わったほうが精度が上がると思われる。
単純に送信時間が長くなると、途中で送信機がぶれた時にビット列が破壊されやすくなる。

**Comment by 0g3** [comment]
だとすると何ビットぐらいがよさそうだろう。
規模感はどれぐらいのイメージ？
最大16人参加とか？　そしたら4ビットで済むけど。

**Comment by Nagisa-Takeuchi** [comment]
精度は実際に試してみないとなんとも……
ユーザーID以外に将来的に攻撃力とかの情報ものせるならそれだけ長くなるやろうし。
とりあえずプロトでは16人ぐらいでいいんじゃないかな？

**Comment by 0g3** [comment]
攻撃力の情報とかはいらない。
サーバー・クライアント間で処理するから。
赤外線の信号にはプレイヤー（送信機）の識別以上の意味は持たせない。

了解。
ver1.0.0は16人参加＝4ビットで行こうか。
